In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("fifa_2022.csv")

In [ ]:
data.head()

Position       Team  Games Played  Win  Draw  Loss  Goals For  \
0         1  Argentina             7    6     0     1         15   
1         2     France             7    5     0     2         16   
2         3    Croatia             7    4     2     1          8   
3         4    Morocco             7    4     1     2          6   
4         5    England             5    3     1     1         13   

   Goals Against  Goal Difference  Points  
0              8                7      18  
1              8                8      15  
2              7                1      14  
3              5                1      13  
4              4                9      10

In [ ]:
data.tail()

Position     Team  Games Played  Win  Draw  Loss  Goals For  \
27        28  Denmark             3    0     1     2          1   
28        29   Serbia             3    0     1     2          5   
29        30    Wales             3    0     1     2          1   
30        31   Canada             3    0     0     3          2   
31        32    Qatar             3    0     0     3          1   

    Goals Against  Goal Difference  Points  
27              3               -2       1  
28              8               -3       1  
29              6               -5       1  
30              7               -5       0  
31              7               -6       0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Position         32 non-null     int64 
 1   Team             32 non-null     object
 2   Games Played     32 non-null     int64 
 3   Win              32 non-null     int64 
 4   Draw             32 non-null     int64 
 5   Loss             32 non-null     int64 
 6   Goals For        32 non-null     int64 
 7   Goals Against    32 non-null     int64 
 8   Goal Difference  32 non-null     int64 
 9   Points           32 non-null     int64 
dtypes: int64(9), object(1)
memory usage: 2.6+ KB


In [ ]:
num_data=data.select_dtypes(include=['int64', 'float64'])
num_data.columns

Index(['Position', 'Games Played', 'Win', 'Draw', 'Loss', 'Goals For',
       'Goals Against', 'Goal Difference', 'Points'],
      dtype='object')

In [ ]:
num_data_columns=['Games Played', 'Win', 'Draw', 'Loss', 'Goals For',
       'Goals Against', 'Goal Difference', 'Points']

In [ ]:
num_data.describe()

Position  Games Played        Win       Draw       Loss  Goals For  \
count  32.000000     32.000000  32.000000  32.000000  32.000000  32.000000   
mean   16.500000      4.000000   1.687500   0.625000   1.687500   5.375000   
std     9.380832      1.344043   1.490562   0.609071   0.592289   4.085774   
min     1.000000      3.000000   0.000000   0.000000   1.000000   1.000000   
25%     8.750000      3.000000   1.000000   0.000000   1.000000   2.750000   
50%    16.500000      3.500000   1.000000   1.000000   2.000000   4.500000   
75%    24.250000      4.250000   2.250000   1.000000   2.000000   6.500000   
max    32.000000      7.000000   6.000000   2.000000   3.000000  16.000000   

       Goals Against  Goal Difference     Points  
count       32.00000        32.000000  32.000000  
mean         5.37500         0.000000   5.687500  
std          2.33832         4.219769   4.431831  
min          1.00000        -8.000000   0.000000  
25%          3.75000        -2.250000   3.000000  
50%          5.00000        -1.000000   4.000000  
75%          7.00000         1.000000   6.750000  
max         11.00000         9.000000  18.000000

In [ ]:
series=pd.DataFrame(num_data)

## Median

In [ ]:
m=series[0:].median()
m

Position           16.5
Games Played        3.5
Win                 1.0
Draw                1.0
Loss                2.0
Goals For           4.5
Goals Against       5.0
Goal Difference    -1.0
Points              4.0
dtype: float64

## Mode

In [ ]:
m=series[0:].mode()
m

Position  Games Played  Win  Draw  Loss  Goals For  Goals Against  \
0          1           3.0  1.0   1.0   2.0        5.0            7.0   
1          2           NaN  NaN   NaN   NaN        NaN            NaN   
2          3           NaN  NaN   NaN   NaN        NaN            NaN   
3          4           NaN  NaN   NaN   NaN        NaN            NaN   
4          5           NaN  NaN   NaN   NaN        NaN            NaN   
5          6           NaN  NaN   NaN   NaN        NaN            NaN   
6          7           NaN  NaN   NaN   NaN        NaN            NaN   
7          8           NaN  NaN   NaN   NaN        NaN            NaN   
8          9           NaN  NaN   NaN   NaN        NaN            NaN   
9         10           NaN  NaN   NaN   NaN        NaN            NaN   
10        11           NaN  NaN   NaN   NaN        NaN            NaN   
11        12           NaN  NaN   NaN   NaN        NaN            NaN   
12        13           NaN  NaN   NaN   NaN        NaN            NaN   
13        14           NaN  NaN   NaN   NaN        NaN            NaN   
14        15           NaN  NaN   NaN   NaN        NaN            NaN   
15        16           NaN  NaN   NaN   NaN        NaN            NaN   
16        17           NaN  NaN   NaN   NaN        NaN            NaN   
17        18           NaN  NaN   NaN   NaN        NaN            NaN   
18        19           NaN  NaN   NaN   NaN        NaN            NaN   
19        20           NaN  NaN   NaN   NaN        NaN            NaN   
20        21           NaN  NaN   NaN   NaN        NaN            NaN   
21        22           NaN  NaN   NaN   NaN        NaN            NaN   
22        23           NaN  NaN   NaN   NaN        NaN            NaN   
23        24           NaN  NaN   NaN   NaN        NaN            NaN   
24        25           NaN  NaN   NaN   NaN        NaN            NaN   
25        26           NaN  NaN   NaN   NaN        NaN            NaN   
26        27           NaN  NaN   NaN   NaN        NaN            NaN   
27        28           NaN  NaN   NaN   NaN        NaN            NaN   
28        29           NaN  NaN   NaN   NaN        NaN            NaN   
29        30           NaN  NaN   NaN   NaN        NaN            NaN   
30        31           NaN  NaN   NaN   NaN        NaN            NaN   
31        32           NaN  NaN   NaN   NaN        NaN            NaN   

    Goal Difference  Points  
0              -2.0     4.0  
1               NaN     NaN  
2               NaN     NaN  
3               NaN     NaN  
4               NaN     NaN  
5               NaN     NaN  
6               NaN     NaN  
7               NaN     NaN  
8               NaN     NaN  
9               NaN     NaN  
10              NaN     NaN  
11              NaN     NaN  
12              NaN     NaN  
13              NaN     NaN  
14              NaN     NaN  
15              NaN     NaN  
16              NaN     NaN  
17              NaN     NaN  
18              NaN     NaN  
19              NaN     NaN  
20              NaN     NaN  
21              NaN     NaN  
22              NaN     NaN  
23              NaN     NaN  
24              NaN     NaN  
25              NaN     NaN  
26              NaN     NaN  
27              NaN     NaN  
28              NaN     NaN  
29              NaN     NaN  
30              NaN     NaN  
31              NaN     NaN

In [ ]:
import numpy as np
from scipy.stats import mode

## Mean

In [ ]:
mean1=np.mean(num_data,axis=0)
mean1

Position           16.5000
Games Played        4.0000
Win                 1.6875
Draw                0.6250
Loss                1.6875
Goals For           5.3750
Goals Against       5.3750
Goal Difference     0.0000
Points              5.6875
dtype: float64

## Median

In [ ]:
meadian1=np.median(num_data,axis=0)
meadian1

array([16.5,  3.5,  1. ,  1. ,  2. ,  4.5,  5. , -1. ,  4. ])

## Mode

In [ ]:
for i in num_data_columns:
    print(i,data[i].mode())

Games Played 0    3
Name: Games Played, dtype: int64
Win 0    1
Name: Win, dtype: int64
Draw 0    1
Name: Draw, dtype: int64
Loss 0    2
Name: Loss, dtype: int64
Goals For 0    5
Name: Goals For, dtype: int64
Goals Against 0    7
Name: Goals Against, dtype: int64
Goal Difference 0   -2
Name: Goal Difference, dtype: int64
Points 0    4
Name: Points, dtype: int64


## Standard Deviation

In [ ]:
std_dev=np.std(num_data)
std_dev

Position           9.233093
Games Played       1.322876
Win                1.467087
Draw               0.599479
Loss               0.582961
Goals For          4.021427
Goals Against      2.301494
Goal Difference    4.153312
Points             4.362034
dtype: float64

## Variance

In [ ]:
variance=np.var(num_data)
variance

Position           85.250000
Games Played        1.750000
Win                 2.152344
Draw                0.359375
Loss                0.339844
Goals For          16.171875
Goals Against       5.296875
Goal Difference    17.250000
Points             19.027344
dtype: float64

## Minimum

In [ ]:
min_value=np.min(num_data,axis=0)
min_value

Position           1
Games Played       3
Win                0
Draw               0
Loss               1
Goals For          1
Goals Against      1
Goal Difference   -8
Points             0
dtype: int64

## Maximum

In [ ]:
max_value=np.max(num_data,axis=0)
max_value

Position           32
Games Played        7
Win                 6
Draw                2
Loss                3
Goals For          16
Goals Against      11
Goal Difference     9
Points             18
dtype: int64

## Percentiles

In [ ]:
percentiles_25=np.percentile(num_data,25,axis=0)
percentiles_25

array([ 8.75,  3.  ,  1.  ,  0.  ,  1.  ,  2.75,  3.75, -2.25,  3.  ])

In [ ]:
percentiles_50=np.percentile(num_data,50,axis=0)
percentiles_50

array([16.5,  3.5,  1. ,  1. ,  2. ,  4.5,  5. , -1. ,  4. ])

In [ ]:
percentiles_75=np.percentile(num_data,75,axis=0)
percentiles_75

array([24.25,  4.25,  2.25,  1.  ,  2.  ,  6.5 ,  7.  ,  1.  ,  6.75])